[bridge_qemu_tap.info]
ipv4 = "192.168.122.100"
bridge = "enp0s6"
defaultGateway = "192.168.122.1"

[bridge_qemu_tap.services.vast]
endpoint = "192.168.122.100:42000"

[bridge_qemu_tap.services.vast-client]
endpoint = "10.0.0.1:42000"
broker = true
pcap.enable = false
pcap.interface = "eth0"

#####
# 2 #
#####
[bridge_qemu_2.info]
ipv4 = "192.168.122.101"
bridge = "enp0s6"
defaultGateway = "192.168.122.1"

[bridge_qemu_2.services.vast]
endpoint = "192.168.122.100:42000"

[bridge_qemu_2.services.vast-client]
endpoint = "192.168.122.100:42000"
broker = true
pcap.enable = false
pcap.interface = "eth0"




[bridge_firecracker_1.info]
ip = "10.0.0.4"

[bridge_firecracker_1.services.vast]
endpoint = "10.0.0.4:42000"

[bridge_firecracker_1.services.vast-client]
endpoint = "10.0.0.1:42000"
broker = true
pcap.enable = false
pcap.interface = "eth0"
